{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "children" : [ {
    "name" : "Test defects",
    "children" : [ {
      "name" : "ValueError: {'code': -32000, 'message': 'connection already closed'}",
      "children" : [ {
        "name" : "test_rpc_call_eth_call",
        "uid" : "e8a4be7df3c48800",
        "parentUid" : "cf7957bfdb0561efc74ada68d6693cf4",
        "status" : "broken",
        "time" : {
          "start" : 1647622771390,
          "stop" : 1647622772106,
          "duration" : 716
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      }, {
        "name" : "test_send_neon_from_one_account_to_another[1]",
        "uid" : "6972c7ee8144c13",
        "parentUid" : "cf7957bfdb0561efc74ada68d6693cf4",
        "status" : "broken",
        "time" : {
          "start" : 1647622839133,
          "stop" : 1647622839810,
          "duration" : 677
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ "1" ]
      } ],
      "uid" : "cf7957bfdb0561efc74ada68d6693cf4"
    } ],
    "uid" : "bdbf199525818fae7a8651db9eafe741"
  }, {
    "name" : "Product defects",
    "children" : [ {
      "name" : "AssertionError: <AssertMessage.CONTAINS_ERROR: 'Contains the error data'>\nassert False\n +  where False = <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f787a162250>>(JsonRpcErrorResponse(id=0, error={'code': -32000, 'message': 'terminating connection due to administrator command\\nser...\\n\\tThis probably means the server terminated abnormally\\n\\tbefore or while processing the request.\\n'}, jsonrpc='2.0'))\n +    where <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f787a162250>> = <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f787a162250>.assert_no_error_object",
      "children" : [ {
        "name" : "test_rpc_call_eth_getLogs_via_tags[latest-latest]",
        "uid" : "e190c5640ed859ed",
        "parentUid" : "9372ff4a89b7db2f05ea50c3cb175466",
        "status" : "failed",
        "time" : {
          "start" : 1647622773697,
          "stop" : 1647622774414,
          "duration" : 717
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ "'latest'", "'latest'" ]
      } ],
      "uid" : "9372ff4a89b7db2f05ea50c3cb175466"
    }, {
      "name" : "AssertionError: <AssertMessage.CONTAINS_ERROR: 'Contains the error data'>\nassert False\n +  where False = <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f787a16c640>>(JsonRpcErrorResponse(id=91, error={'code': -32000, 'message': 'connection already closed'}, jsonrpc='2.0'))\n +    where <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f787a16c640>> = <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f787a16c640>.assert_no_error_object",
      "children" : [ {
        "name" : "test_rpc_call_eth_getLogs_via_tags[latest-earliest]",
        "uid" : "d00a716e650a169f",
        "parentUid" : "31ef64642c09b96a0b415ad6284f1f9e",
        "status" : "failed",
        "time" : {
          "start" : 1647622775875,
          "stop" : 1647622776591,
          "duration" : 716
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ "'latest'", "'earliest'" ]
      } ],
      "uid" : "31ef64642c09b96a0b415ad6284f1f9e"
    }, {
      "name" : "AssertionError: <AssertMessage.CONTAINS_ERROR: 'Contains the error data'>\nassert False\n +  where False = <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f787a0fad30>>(JsonRpcErrorResponse(id=75, error={'code': -32000, 'message': 'terminating connection due to administrator command\\nse...\\n\\tThis probably means the server terminated abnormally\\n\\tbefore or while processing the request.\\n'}, jsonrpc='2.0'))\n +    where <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f787a0fad30>> = <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f787a0fad30>.assert_no_error_object",
      "children" : [ {
        "name" : "test_rpc_call_eth_getLogs_via_tags[latest-pending]",
        "uid" : "ba311186fde4301",
        "parentUid" : "7a603fb098a7f9680407ab61d72917e5",
        "status" : "failed",
        "time" : {
          "start" : 1647622776604,
          "stop" : 1647622777320,
          "duration" : 716
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ "'latest'", "'pending'" ]
      } ],
      "uid" : "7a603fb098a7f9680407ab61d72917e5"
    }, {
      "name" : "AssertionError: <AssertMessage.CONTAINS_ERROR: 'Contains the error data'>\nassert False\n +  where False = <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f787a0a2040>>(JsonRpcErrorResponse(id=16, error={'code': -32000, 'message': 'connection already closed'}, jsonrpc='2.0'))\n +    where <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f787a0a2040>> = <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f787a0a2040>.assert_no_error_object",
      "children" : [ {
        "name" : "test_rpc_call_eth_getLogs_via_numbers",
        "uid" : "da5f91839e3f2208",
        "parentUid" : "26777c38f72a7669fc20207d301872d6",
        "status" : "failed",
        "time" : {
          "start" : 1647622777332,
          "stop" : 1647622778047,
          "duration" : 715
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      } ],
      "uid" : "26777c38f72a7669fc20207d301872d6"
    }, {
      "name" : "AssertionError: The response type is error response\nassert False\n +  where False = <bound method BasicTests.assert_is_successful_response of <integration.tests.basic.test_transactions.TestRpcCallsTransactions object at 0x7f787a0940a0>>(JsonRpcErrorResponse(id=69, error={'code': -32000, 'message': 'connection already closed'}, jsonrpc='2.0'))\n +    where <bound method BasicTests.assert_is_successful_response of <integration.tests.basic.test_transactions.TestRpcCallsTransactions object at 0x7f787a0940a0>> = <integration.tests.basic.test_transactions.TestRpcCallsTransactions object at 0x7f787a0940a0>.assert_is_successful_response",
      "children" : [ {
        "name" : "test_rpc_call_eth_sendRawTransaction",
        "uid" : "7047d24e33165356",
        "parentUid" : "84996237c971c6203dad69f193537fdb",
        "status" : "failed",
        "time" : {
          "start" : 1647622828262,
          "stop" : 1647622828927,
          "duration" : 665
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      } ],
      "uid" : "84996237c971c6203dad69f193537fdb"
    } ],
    "uid" : "8fb3a91ba5aaf9de24cc8a92edc82b5d"
  } ],
  "name" : "categories"
}